image: Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
  - Release

environment:
  CTEST_OUTPUT_ON_FAILURE: True
  MSVC_VERSION: 16
  PYTHON: "C:\\Python37-x64"
  BUILD_NAME: master

install:
  # Fetch and setup conan
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - "%PYTHON%\\python.exe -m pip --quiet install conan"
  - conan remote add barco %CONAN_URL%
  - conan user -p %CONAN_API_KEY% -r barco conan

  # Install Ninja
  - set NINJA_URL="https://github.com/ninja-build/ninja/releases/download/v1.6.0/ninja-win.zip"
  - appveyor DownloadFile %NINJA_URL% -FileName ninja.zip
  - 7z x ninja.zip -oC:\projects\deps\ninja > nul
  - del ninja.zip
  - set PATH=C:\projects\deps\ninja;%PATH%
  
  # Visual Studio's compiler information
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvars64.bat"

before_build:
  - conan profile new default --detect
  - conan profile update settings.compiler="Visual Studio" default
  - conan profile update settings.compiler.version=%MSVC_VERSION% default
  - if "%APPVEYOR_REPO_TAG%" == "true" (set BUILD_NAME=%APPVEYOR_REPO_TAG_NAME:v=%)

build_script:
  - conan create --ignore-dirty %APPVEYOR_BUILD_FOLDER% %APPVEYOR_PROJECT_NAME%/%BUILD_NAME%@barco/healthcare -s build_type=%configuration%

after_test:
  - if "%APPVEYOR_REPO_BRANCH%" == "master" ( conan upload --remote barco --all --force %APPVEYOR_PROJECT_NAME%/%BUILD_NAME%@barco/healthcare )
  - if "%APPVEYOR_REPO_TAG%" == "true" ( conan upload --remote barco --all %APPVEYOR_PROJECT_NAME%/%BUILD_NAME%@barco/healthcare )


# uncomment following lines to be able to debug the appveyor image through RDP protocol when build finished
# https://www.appveyor.com/docs/how-to/rdp-to-build-worker/
# on_finish:
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

